on:
  push:
    branches:
      - "fs-1263-publish-fork"
env:
  VERSION: "0.0.1"
  IMAGE_NAME_STUB: "digital-form-builder-dluhc-"
  IMAGE_REPO_PATH: "ghcr.io/${{github.repository_owner}}"

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
    steps:
      - id: set-vars
        run: |
          echo "::set-output name=LOWER_CASE_BRANCH::$(
            echo ${GITHUB_REF#refs/heads/} |
            tr "[:upper:]" "[:lower:]"
          )"
      - name: echo-vars
        id: echo-vars
        run: |
          echo ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
          echo $VERSION

  read-env-vars:
    needs: setup-env-vars
    runs-on: ubuntu-latest
    steps:
      - id: read-vars
        run: |
          echo Lower case branch name: ${{needs.setup-env-vars.outputs.BRANCH_NAME}}
          echo Version: $VERSION
          echo Image name stub: $IMAGE_NAME_STUB
          echo Image repo path: $IMAGE_REPO_PATH
          echo Full image repo path stub: $IMAGE_REPO_PATH/$IMAGE_NAME_STUB
