on:
  push:
    branches:
      - "fs-1263-publish-fork"
env:
  VERSION: "0.0.1"
  IMAGE_NAME_STUB: "digital-form-builder-dluhc-"
  IMAGE_REPO_PATH: "ghcr.io/${{github.repository_owner}}"

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
    steps:
      - id: set-vars
        run: |
          echo "::set-output name=LOWER_CASE_BRANCH::$(
            echo ${GITHUB_REF#refs/heads/} |
            tr "[:upper:]" "[:lower:]"
          )"
      - name: echo-vars
        id: echo-vars
        run: |
          echo ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
          echo $VERSION

  read-env-vars:
    needs: setup-env-vars
    runs-on: ubuntu-latest
    steps:
      - id: read-vars
        run: |
          echo Lower case branch name: ${{needs.setup-env-vars.outputs.BRANCH_NAME}}
          echo Version: $VERSION
          echo Image name stub: $IMAGE_NAME_STUB
          echo Image repo path: $IMAGE_REPO_PATH
          echo Full image repo path stub: $IMAGE_REPO_PATH/$IMAGE_NAME_STUB

  mock-tag-and-push-image:
    needs: setup-env-vars
    runs-on: ubuntu-latest
    env:
      matrix_app_mock: runner
    steps:
      - id: tag-and-push
        name: Tag and push (all branches)
        run: |
          echo docker tag $IMAGE_NAME_STUB$matrix_app_mock $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:${{ github.sha }}
          echo docker tag $IMAGE_NAME_STUB$matrix_app_mock $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:$VERSION
          echo docker tag $IMAGE_NAME_STUB$matrix_app_mock $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:${{needs.setup-env-vars.outputs.BRANCH_NAME}}

          echo docker push $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:${{ github.sha }}
          echo docker push $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:$VERSION
          echo docker push $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:${{needs.setup-env-vars.outputs.BRANCH_NAME}}
      - id: tag-and-push-latest
        name: Tag and Push Latest (if main)
        if: needs.setup-env-vars.outputs.BRANCH_NAME == 'fs-1263-publish-fork'
        run: |
          echo docker tag $IMAGE_NAME_STUB$matrix_app_mock $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:latest
          echo docker push $IMAGE_REPO_PATH/$IMAGE_NAME_STUB$matrix_app_mock:latest
