on:
  push:
    branches:
      - "fs-1263-publish-fork"
env:
  VERSION: "0.0.1"
  BRANCH: ${GITHUB_REF}

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: do-vars
        id: do-vars
        run: |
          echo $VERSION
          echo $BRANCH
          echo "::set-output name=LOWER_CASE_BRANCH::$(
            echo ${GITHUB_REF#refs/heads/} |
            tr "[:upper:]" "[:lower:]"
          )"
      - id: read-vars
        run: |
          echo ${{steps.do-vars.outputs.LOWER_CASE_BRANCH}}
