on:
  push:
    branches:
      - "fs-1263-publish-fork"
env:
  VERSION: "0.0.1"

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
    steps:
      - id: set-vars
        run: |
          echo "::set-output name=LOWER_CASE_BRANCH::$(
            echo ${GITHUB_REF#refs/heads/} |
            tr "[:upper:]" "[:lower:]"
          )"
      - name: echo-vars
        id: echo-vars
        run: |
          echo ${{steps.set-vars.outputs.LOWER_CASE_BRANCH}}
          echo $VERSION

  read-env-vars:
    needs: setup-env-vars
    runs-on: ubuntu-latest
    steps:
      - id: read-vars
        run: |
          echo ${{needs.setup-env-vars.outputs.BRANCH_NAME}}
