name: Dispatch to external repositories

on:
  push:
    branches: chore/notify-ho
    tags:
      - '*'

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/notifications.json)
          echo ::set-output name=matrix::${JSON//'%'/'%25'}
  notify:
    runs-on: ubuntu-latest
    needs: parse
    strategy:
      matrix: ${{fromJson(needs.parse.outputs.matrix)}}
    steps:
      # Create check run
    - name: Dump event content
    - uses: octokit/request-action@v2.x
      with:
        route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
        owner: ${{matrix.owner}}
        repo: ${{matrix.repo}}
        worklow_id: ${{matrix.workflow_id}}
        sha: ${{github.sha}}
        tag: ${{contains(github.ref, '/refs/tags/') && github.ref}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
