name: Dispatch to external repositories

on:
  push:
    branches: chore/notify-ho

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        run: |
          curl -X POST https://api.github.com/repos/UKHomeOffice/digital-form-builder-1/actions/workflows/4763518/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.WORKFLOW_PAT }} \
          --data '{"event_type": "xgovformbuilder-updated", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

