name: Dispatch to external repositories

on:
  push:
    branches: chore/notify-ho
    tags:
      - '*'

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/notifications.json)
          echo ::set-output name=matrix::${JSON//'%'/'%25'}
  notify:
    runs-on: ubuntu-latest
    needs: parse
    strategy:
      matrix: ${{fromJson(needs.parse.outputs.matrix)}}
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{matrix.owner}}
          repo: ${{matrix.repo}}
          sha: ${{github.event.inputs.sha}}
          tag: ${{github.event.inputs.tags}}

      #- name: Repository dispatch



#        run: |
#          curl -X POST  ${{ matrix.endpoint }} \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.WORKFLOW_PAT }} \
#          --data '{ "ref": "${{matrix.branch}}", "inputs":{ "sha": "$GITHUB_SHA"} }'
