name: Publish to Github Container Registry

on:
  push:
    branches:
      - master
      - chore/notify-ho

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ designer, runner ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and publish ${{ matrix.app }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./${{matrix.app}}/Dockerfile
          tags: |
            ghcr.io/xgovformbuilder/digital-form-builder-${{ matrix.app }}:${{ github.run_number }}-rc

      - name: Trigger deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Development Environment
          token: ${{ secrets.GHCR_PAT }}
          inputs: '{ "app": "${{ matrix.app }}"}'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Tag master with run number
        run: |
          git tag ${{github.run_number}}-rc
          git push --tags origin HEAD
