name: Testing versioning
env:
  DOCKER_TAG_BASE_VERSION: "0.0.3"
  TAG_APPEND: ""
on:
  push:
    branches:
      - fs-1263-publish-fork
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.set_version.outputs.tag_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Read Lower case branch name
        if: github.ref != 'refs/heads/main'
        id: lower
        run: >-
          echo "::set-output name=TAG_APPEND::_$(
            echo ${{ github.ref_name }} |
            tr "[:upper:]" "[:lower:]"
          )"
      - name: Set Branch version
        id: set_version
        if: github.ref != 'refs/heads/main'
        env:
          TAG_APPEND: ${{ lower.outputs.TAG_APPEND }}
        run: echo "::set-output name=tag_version::$(echo $DOCKER_TAG_BASE_VERSION)$(echo $TAG_APPEND)"

  check-semver:
    runs-on: ubuntu-latest
    needs: [calculate-version]
    env:
      SEMVER: ${{ needs.calculate-version.outputs.tag_version }}
    steps:
      - run: |
          echo SEMVER: $SEMVER
